#!/bin/bash
FILE="data.json"
NAME=$(jq -r '.name' "$FILE" | sed 's/.*/\u&/')
HEIGHT=$(jq -r '.height' "$FILE" | awk '{printf "%.1f", $1/10}')
WEIGHT=$(jq -r '.weight' "$FILE" | awk '{printf "%.0f", $1/10}')
TYPE=$(jq -r '.types[0].type.name' "$FILE" | sed 's/.*/\u&/')
echo "$NAME is of type $TYPE, weighs ${WEIGHT}kg, and is ${HEIGHT}m tall."
